apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: iicyt65mn-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/iicyt65mn-java-quarkus-gitops